Hello Microverse project
CrackedYoda/Microverse-Linters pull request #1
Opened 2023-05-31 08:37 UTC by CrackedYoda

pull request for my hello microverse project

2023-05-31 09:29 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @CrackedYoda , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._
- [ ] Kindly update your readme file completely include details on how your project can be clone and also usage
- [ ] your readme 
![Screenshot 2023-05-31 101743](https://github.com/CrackedYoda/Microverse-Linters/assets/92458236/4846f012-d862-434c-ae88-a04e592e9de6)

- [ ] Please kindly includes socaial media handle links ,your twitter handle ,githube handle link and linkedin handle links this are so much essential the recruilter can easily contact you easily.
- [ ] Kindly add your Mit license to include this details by follow this link and edit to fit your project also make sure you edit it to add your name as the owner of the project likewise remove all placeholder text.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 09:29 UTC, ademibowale commented on index.html
> +</body>
- [ ] According to the project requirement kindly consider using html file that includes a header with the text "Hello Microverse!". Use h1 tag for that for proper semantic usage.

2023-05-31 09:29 UTC, ademibowale commented on style.css
> +h1 { color: aqua; }
- [ ] A ccording to project requirement kindly consider using .css file that includes one class with styles for your header (make it in your favorite color).

2023-06-01 14:03 UTC, Ofarouq310 requested changes
Hi @CrackedYoda , ✋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🥈 

![giphy](https://github.com/AliRezaBmeDu/HelloMicroverse/assets/102612396/6b5491d5-ffe0-4e31-990f-1e6191a27349)

 ## Highlights
✅ No linters errors.
✅ Descriptive PR summary.

 ## Required Changes ♻️

- As requested by the previous reviewer, we need to work a bit on the `README` file, lets discuss what we need to change: 

  - [ ] Kindly remove any placeholder like the one in the image as it was just there for guidance, leaving it may seem inappropriate and unprofessional.
![image](https://github.com/CrackedYoda/Microverse-Linters/assets/102612396/064cc8a9-5861-4820-884a-446b2b91b2c1)

  - [ ] For your author link handlers, please use the same template as in the image, just remove the red-underlined parts and write your username instead depending on the platform.
![image](https://github.com/CrackedYoda/Microverse-Linters/assets/102612396/416c9a21-44fe-4a53-b8d6-49593ea7acb4)

  - [ ] There are 2 sections that can only be removed, first of all, which is an optional section, the `FAQ` section, and the `Live Demo` section in case you still do not have a deployment link for your project, every other section should be included in your `README`.

   - [ ] Kindly add LICENSE to your project files, since its link does not work. Please watch this [tutorial](https://www.youtube.com/watch?v=8Dm7XXvtqXI) to know how to add one, remember to use the `MIT` license.

- Please refer to the [MIcroverse README template](https://github.com/microverseinc/readme-template) to get a better understanding of what you need to do.


_Check the comments under the review._

## Optional suggestions

- Kindly make sure that your commit messages are always capitalized and are in imperative tense.

-  As for the PR description, you should simplify it even more, just summarizing what you added in a bullet list or number list, take a look at this example, to edit the description, just click on three dots on the right side, then click on edit.
![image](https://github.com/Fentahunn/portfolio_one/assets/102612396/f16c077a-f8e1-4035-9cf4-cfe78dac955b)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 14:03 UTC, Ofarouq310 commented on style.css
> +h1 { color: aqua; }
- [ ] As requested by the previous reviewer, kindly instead of using the `h1` sector to style your header, use an `id` or `class` instead, add the class name or id name in your HTML to your title, then call it in the CSS file by the corresponding selector.

2023-06-01 14:37 UTC, CrackedYoda commented on style.css
> +h1 { color: aqua; }
my social handle links all work and the MIT license link is functional and i did as directed by the MIT help page and every other section of the readme is present
i don't understand why you would stop the approval of this project

2023-06-02 09:21 UTC, Cabraham1 approved these changes
Hi @CrackedYoda  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 09:29 UTC, merged